---
# - name: chkrootkit | set config file path for modern Debian-based distros
#   set_fact:
#     chkrootkit_conf: "/etc/chkrootkit/chkrootkit.conf"
#   when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 22) or
#         (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 12)

# - name: chkrootkit | set config file path for old Debian-based distros
#   set_fact:
#     chkrootkit_conf: "/etc/chkrootkit.conf"
#   when: not ((ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 22) or
#         (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 12))

- name: Chkrootkit | set config file path for qs5779
  ansible.builtin.set_fact:
    chkrootkit_conf: "/etc/chkrootkit/chkrootkit.conf"

- name: Chkrootkit | install tool from repo
  ansible.builtin.package:
    name: Chkrootkit
    state: present
    update_cache: true

- name: Chkrootkit | enable daily scheduled runs
  ansible.builtin.lineinfile:
    dest: "{{ chkrootkit_conf }}"
    regexp: "^RUN_DAILY="
    line: "RUN_DAILY=\"true\""
    state: present
    mode: "0644"

- name: Chkrootkit | setup receiver email address for reports
  ansible.builtin.lineinfile:
    dest: "{{ chkrootkit_conf }}"
    line: "REPORT_EMAIL=\"{{ antirootkits_mail_to }}\""
    state: present
    mode: "0644"

- name: Chkrootkit | install logrotate config
  ansible.builtin.template:
    src: chkrootkit.logrotate
    dest: /etc/logrotate.d/chkrootkit
    owner: root
    group: root
    mode: "0644"

- name: Chkrootkit | install cron job
  ansible.builtin.template:
    src: chkrootkit.cron.j2
    dest: /etc/cron.daily/chkrootkit
    owner: root
    group: root
    mode: "0755"
  when: ansible_os_family != "Debian"  # qs5779 handles this in playbook
