---
# tasks file for qs5779.antirootkits

- name: Antirootkits | antirootkits_mail_from variable should be defined
  ansible.builtin.assert:
    that:
      - antirootkits_mail_from is defined and antirootkits_mail_from | length > 0
    msg: "Set the value of 'antirootkits_mail_from' in either the inventory file or the playbook invoking this role."

- name: Antirootkits | antirootkits_mail_to variable should be defined
  ansible.builtin.assert:
    that:
      - antirootkits_mail_to is defined and antirootkits_mail_to | length > 0
    msg: "Set the value of 'antirootkits_mail_to' in either the inventory file or the playbook invoking this role."

- name: Antirootkits | load OS Family specific defaults
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: ['rkhunter', 'chkrootkit', 'unhide', 'shelldetector']

- name: Antirootkits | Rkhunter
  ansible.builtin.include_tasks: rkhunter.yml
  when: rkhunter
  tags: ['rkhunter']

- name: Antirootkits | chkrootkit
  ansible.builtin.include_tasks: chkrootkit.yml
  when:
    - chkrootkit
    - ansible_os_family == "Debian"
  tags: ['chkrootkit']

- name: Antirootkits | Unhide
  ansible.builtin.include_tasks: unhide.yml
  when: unhide
  tags: ['unhide']

- name: Antirootkits | Shell Detector
  ansible.builtin.include_tasks: shelldetector.yml
  when: shelldetector
  tags: ['shelldetector']
