---

- name: Unhide | install prerequisites
  ansible.builtin.package:
    name:
      - epel-release
    state: present
    update_cache: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Unhide | install tool from repo
  ansible.builtin.package:
    name: unhide
    state: present
    update_cache: true

- name: Unhide | create log directory
  ansible.builtin.file:
    path: "{{ unhide_log_directory }}"
    mode: "0750"
    owner: root
    group: root
    state: directory

- name: Unhide | install cron script
  ansible.builtin.template:
    src: unhide.cron.j2
    dest: "/usr/local/bin/unhide_cron.sh"
    owner: root
    group: root
    mode: "0750"

- name: Unhide | creates daily cronjob
  ansible.builtin.cron:
    name: "Launch Unhide audit"
    hour: "{{ unhide_cron_hour }}"
    minute: "{{ unhide_cron_minute }}"
    weekday: "*"
    cron_file: "unhide"
    user: "root"
    job: "/usr/local/bin/unhide_cron.sh 2>&1 | logger"
